// model.js

// ===========================
// model.js — Defines the DueItem class
// ===========================
//
// Each due item represents a deadline, payment, event, or obligation.
// It stores metadata such as title, due date, optional amount, category,
// priority, and completion status (done or not).
//
// This class can be extended later (e.g., for recurring dues).
// ===========================

export class DueItem {
  /**
   * @param {Object} data - The initial data for the due item
   * @param {string} data.title - Title or short description of the due
   * @param {string} [data.category] - Category label (finance, project, etc.)
   * @param {string} data.dueDate - ISO date string (yyyy-mm-dd)
   * @param {number} [data.amount] - Optional amount or cost
   * @param {string} [data.priority] - Priority level ("high" | "medium" | "low")
   * @param {boolean} [data.done] - Completion status
   * @param {string} [data.id] - Unique identifier (autogenerated if missing)
   */
  constructor({
    title,
    category = "other",
    dueDate,
    amount = 0,
    priority = "medium",
    done = false,
    id = crypto.randomUUID(),
  }) {
    this.id = id;
    this.title = title.trim();
    this.category = category;
    this.dueDate = dueDate;
    this.amount = Number(amount) || 0;
    this.priority = priority;
    this.done = done;
    this.createdAt = new Date().toISOString();
  }

  /**
   * Returns true if the due date has passed and the item is not marked done.
   */
  get isOverdue() {
    return !this.done && new Date(this.dueDate) < new Date();
  }

  /**
   * Returns number of days until the due date (negative if overdue).
   */
  get daysRemaining() {
    const today = new Date();
    const due = new Date(this.dueDate);
    return Math.ceil((due - today) / (1000 * 60 * 60 * 24));
  }

  /**
   * Marks the item as completed.
   */
  markDone() {
    this.done = true;
  }

  /**
   * Converts to plain JSON for storage (used by localStorage).
   */
  toJSON() {
    return {
      id: this.id,
      title: this.title,
      category: this.category,
      dueDate: this.dueDate,
      amount: this.amount,
      priority: this.priority,
      done: this.done,
      createdAt: this.createdAt,
    };
  }
}
